name: Lint
on:
  pull_request:
permissions:
  contents: read
jobs:
  build:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
      - name: Lint files
        run: |
          ./build.sh lint
